### PR TITLE
Do not ignore values that are 0 or false.

### PR DESCRIPTION
**Pull request by neredera**
Report values that are 0 or false.

### CODE REVIEW

**Comment by neredera** [comment]
Seems to have a problem with HmIP devices that have not sent a value to the ccu.

**Comment by sfudeus** [comment]
@neredera Stumbled myself about this issue yesterday (because a power-value of a HmIP-FSM was never reset to 0). What problem did you see with your proposed fix? Does it make worse than the bug we have or just not complete?

**Comment by sfudeus** [comment]
However, this seems a lot more reasonable than the current behaviour. With this, only empty string values and missing values will be ignored, currently 0 is ignored, too, which definitely is wrong. And if devices pending an initialization wrongly report 0 instead if their correct value and would now be measured as "0", this is definitely a lot less frequent the case.

**Comment by neredera** [comment]
I tried to use the overload of getParamSet (see this [commit](https://github.com/neredera/homematic_exporter/commit/49432cae621cf8d84718601bf9feba2736947a00)) that returns if the value is undefined.
I think it works for IP devices correct, but it still returns after a restart of the exporter 0 for Bidcos Devices that are unavailable (e.g. battery empty).

**Pull request merged**
